version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "payments"

  dev:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      DB_HOST: db
      DB_NAME: "payments"
      DB_PASSWORD: "admin"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  tests:
    build: .
    command: pytest -vv
    volumes:
      - .:/app

  flake8:
    build: .
    command: flake8 .
    volumes:
      - .:/app
